# Generated by Django 5.0.7 on 2024-07-25 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 22, 29, 36, 744363), verbose_name='fecha_creacion'),
        ),
    ]
